dbt_example:
  outputs:
    dev:
      dataset: dbt_example
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: EU
      method: oauth
      priority: interactive
      project: "{{ env_var('GCP_DEV_PROJECT') }}"
      threads: 8
      type: bigquery
  target: dev

elementary:
  outputs:
    default:
      type: bigquery
      method: oauth
      project: "{{ env_var('GCP_DEV_PROJECT') }}"
      dataset: dbt_example_elementary
      location: EU
      threads: 8
